### ISSUE TITLE
BNO055 instance fail unless with frequency arg. BNO055 polling unstable, fails invariably

### ISSUE THREAD

**Issue by iani** [adafruit/Adafruit_CircuitPython_BNO055#12]
Hello,
I am posting this after seeing a similar issue on the CCS811 here:
https://github.com/adafruit/Adafruit_CircuitPython_CCS811/issues/9

I am experiencing exactly the same problems, with write fail like this:
  File "adafruit_bus_device/i2c_device.py", line 102, in write
Example: 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ccs811_example.py", line 10, in <module>
  File "adafruit_ccs811.py", line 113, in __init__
  File "adafruit_register/i2c_bit.py", line 40, in __get__
  File "adafruit_register/i2c_bit.py", line 39, in __get__
  File "adafruit_bus_device/i2c_device.py", line 102, in write
OSError: [Errno 5] EIO

I tried creating both busio and bitbangio instances with frequency set to 10000.  This works: 

`
i2c_bus = bitbangio.I2C(board.SCL, board.SDA, frequency=10000) # was 10000
`

But always after some time interval, there is a write error, like this: 

Accelerometer (m/s^2): (162.55, -123.85, -30.97)
Magnetometer (microteslas): (2036.0, -0.0625, -0.0625)
Traceback (most recent call last):
  File "main.py", line 73, in <module>
  File "adafruit_bno055.py", line 76, in __get__
  File "adafruit_register/i2c_struct.py", line 58, in __get__
  File "adafruit_register/i2c_struct.py", line 57, in __get__
  File "adafruit_bus_device/i2c_device.py", line 102, in write
OSError: [Errno 19] ENODEV

I tried different frequencies and different delay times between polling intervals, to no avail.

Is there a way to stabilize the behavior of the sensor and the library?

Thank you!

Iannis Zannos

**Comment by caternuson** [comment]
This is probably related to #9

**Comment by kattni** [comment]
@iani Are you still experiencing this issue?
