### ISSUE TITLE
Not Running Properly (server.py and setup.py)

### ISSUE THREAD

**Issue by MrDrStevenson** [adafruit/Adafruit_CircuitPython_BNO055#74]
I am running python 2.7.16 and I am using an installation that to my knowledge, was working.  Upon trying to run server.py (or any of the simpletests), I am given the error message below (with the corresponding line number 2 for the simpletests):
Traceback (most recent call last):
  File "server.py", line 34, in <module>
    import board
ImportError: No module named board

I figured that there was just something wrong with the installation, so I proceeded to try to run the install with setup.py and I was greeted with this long traceback error.  I have no idea what's causing it.  I just did a fresh install of python and was greeted with the same errors.  Any help would be appreciated.

debian@beaglebone:~/Adafruit_CircuitPython_BNO055$ sudo python setup.py
/tmp/easy_install-_gKWbh/setuptools_scm-6.0.1/src
<pkg_resources.WorkingSet object at 0xb5e3cef0>
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    py_modules=["adafruit_bno055"],
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 144, in s                                                                                                                                                             etup
    _install_setup_requires(attrs)
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 139, in _                                                                                                                                                             install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 724, in fetch                                                                                                                                                             _build_eggs
    replace_conflicting=True,
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 782, i                                                                                                                                                             n resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1065,                                                                                                                                                              in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1077,                                                                                                                                                              in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 791, in fetch                                                                                                                                                             _build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", li                                                                                                                                                             ne 704, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", li                                                                                                                                                             ne 730, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", li                                                                                                                                                             ne 915, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", li                                                                                                                                                             ne 1183, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", li                                                                                                                                                             ne 1169, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in ru                                                                                                                                                             n_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in se                                                                                                                                                             tup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in sa                                                                                                                                                             ve_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in re                                                                                                                                                             sume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in sa                                                                                                                                                             ve_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in se                                                                                                                                                             tup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in ru                                                                                                                                                             n_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _ex                                                                                                                                                             ecfile
    exec(code, globals, locals)
  File "/tmp/easy_install-_gKWbh/setuptools_scm-6.0.1/setup.py", line 52, in <mo                                                                                                                                                             dule>
    keywords="adafruit 9-dof absolute orientation accelerometer velocity tempera                                                                                                                                                             ture gravity"
  File "/tmp/easy_install-_gKWbh/setuptools_scm-6.0.1/setup.py", line 29, in scm                                                                                                                                                             _config
    url="https://github.com/adafruit/Adafruit_CircuitPython_BNO055",
  File "/tmp/easy_install-_gKWbh/setuptools_scm-6.0.1/src/setuptools_scm/__init_                                                                                                                                                             _.py", line 8, in <module>
  File "/tmp/easy_install-_gKWbh/setuptools_scm-6.0.1/src/setuptools_scm/config.                                                                                                                                                             py", line 6, in <module>
  File "/tmp/easy_install-_gKWbh/setuptools_scm-6.0.1/src/setuptools_scm/utils.p                                                                                                                                                             y", line 41
    print(*k)

**Comment by ladyada** [comment]
py 2 is not supported, use 3
