### ISSUE TITLE
[Question] Can I use this package on Jetson Xavier NX module?

### ISSUE THREAD

**Issue by JAICHANGPARK** [adafruit/Adafruit_CircuitPython_BNO055#94]
Hi~

I had some problem using this library on Jetson Xavier NX Board

### Test Code 

```
import busio
import board
import adafruit_bno055


sensor = adafruit_bno055.BNO055_I2C(busio.I2C(board.SCL_1, board.SDA_1)) 
```

### Error 

```
Traceback (most recent call last):
  File "board_test.py", line 48, in <module>
    import adafruit_bno055
  File "/home/javier/.local/lib/python3.6/site-packages/adafruit_bno055.py", line 35, in <module>
    from adafruit_bus_device.i2c_device import I2CDevice
  File "/home/javier/.local/lib/python3.6/site-packages/adafruit_bus_device/i2c_device.py", line 25, in <module>
    class I2CDevice:
  File "/home/javier/.local/lib/python3.6/site-packages/adafruit_bus_device/i2c_device.py", line 55, in I2CDevice
    def __init__(self, i2c: I2C, device_address: int, probe: bool = True) -> None:
NameError: name 'I2C' is not defined
Exiting... 
Cleaning up pins
```

**Comment by tekktrik** [comment]
Hi @JAICHANGPARK, this is a single board computer, right?  There was a happenstance in some of the libraries using Blinka that show this issue.  If you upgrade Blinka to version 7.0.0+, I think that should fix it.

**Comment by JAICHANGPARK** [comment]
@tekktrik Thank you 
I will check again !

**Comment by tekktrik** [comment]
@JAICHANGPARK did this end of fixing the problem?

**Comment by ladyada** [comment]
closing due to no response
